name: Hello GitHub Actions
on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - run: echo "Github Actions!!"
  goodbye-job:
    runs-on: ubuntu-latest
    steps:
      - run: cho "Goodbye, GitHub Actions."